# Generated by Django 5.2.6 on 2025-09-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('equipment', 'Equipment'), ('accessories', 'Accessories'), ('merchandise', 'Merchandise')], default='update', max_length=20),
        ),
    ]
